id: TestIsValueInArray
version: -1
name: TestIsValueInArray
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1d184e9b-8c63-418b-886f-58a89e885935
    type: start
    task:
      id: 1d184e9b-8c63-418b-886f-58a89e885935
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 3e81105a-e953-44f1-8d2d-74da732a0636
    type: regular
    task:
      id: 3e81105a-e953-44f1-8d2d-74da732a0636
      version: -1
      name: Create array in context
      description: Find all users associated with a role
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append: {}
      key:
        simple: myArray
      roles: {}
      value:
        simple: ${.=function(obj){return ['value1','value2','value3']}(val)}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 2ff6e191-8224-4063-819d-051d7e222111
    type: condition
    task:
      id: 2ff6e191-8224-4063-819d-051d7e222111
      version: -1
      name: Check existing value
      description: Look for value in a list
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "4"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 3ef6ac3b-7185-45ce-83a8-f33e34be151a
    type: regular
    task:
      id: 3ef6ac3b-7185-45ce-83a8-f33e34be151a
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 777f5f4c-359e-409e-81bd-a26761a05933
    type: condition
    task:
      id: 777f5f4c-359e-409e-81bd-a26761a05933
      version: -1
      name: Check a non exist value
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value5
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: e2528c67-2c27-454b-8662-3fee91e91345
    type: regular
    task:
      id: e2528c67-2c27-454b-8662-3fee91e91345
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: ecf1380c-c193-4ffc-89d2-47be0c5a3fe1
    type: condition
    task:
      id: ecf1380c-c193-4ffc-89d2-47be0c5a3fe1
      version: -1
      name: 'Check two equal strings '
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "8"
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: value
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 7dfaa838-c65b-4d52-8d4b-7fed82e9962a
    type: regular
    task:
      id: 7dfaa838-c65b-4d52-8d4b-7fed82e9962a
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: f655cbe2-411f-4812-856b-88d05c690398
    type: condition
    task:
      id: f655cbe2-411f-4812-856b-88d05c690398
      version: -1
      name: 'Check two non equal strings '
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "11"
      "yes":
      - "9"
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 41c6b0e4-0550-4810-8b2a-6245c4361c92
    type: regular
    task:
      id: 41c6b0e4-0550-4810-8b2a-6245c4361c92
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 6abec9c3-8259-4111-88e4-8961d137e013
    type: condition
    task:
      id: 6abec9c3-8259-4111-88e4-8961d137e013
      version: -1
      name: Check empty array
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "12"
    scriptarguments:
      array: {}
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: f42eb355-9200-4ae3-845e-944897cafee5
    type: regular
    task:
      id: f42eb355-9200-4ae3-845e-944897cafee5
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 919fcd3a-00da-4872-8b2a-9d17600792fe
    type: condition
    task:
      id: 919fcd3a-00da-4872-8b2a-9d17600792fe
      version: -1
      name: Check empty value
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
      - "15"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: value
      right: {}
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 5636c349-f28c-406d-80fa-1f75b51baa92
    type: regular
    task:
      id: 5636c349-f28c-406d-80fa-1f75b51baa92
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 9b192a4a-f992-4b53-8713-a1d5ed9181b2
    type: title
    task:
      id: 9b192a4a-f992-4b53-8713-a1d5ed9181b2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 1435
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1465,
        "width": 1885,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
